/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FacultyBlogRouteImport } from './routes/faculty-blog'
import { Route as DigitalInitiativesRouteImport } from './routes/digital-initiatives'
import { Route as IndexRouteImport } from './routes/index'

const FacultyBlogRoute = FacultyBlogRouteImport.update({
  id: '/faculty-blog',
  path: '/faculty-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalInitiativesRoute = DigitalInitiativesRouteImport.update({
  id: '/digital-initiatives',
  path: '/digital-initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-initiatives': typeof DigitalInitiativesRoute
  '/faculty-blog': typeof FacultyBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-initiatives': typeof DigitalInitiativesRoute
  '/faculty-blog': typeof FacultyBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-initiatives': typeof DigitalInitiativesRoute
  '/faculty-blog': typeof FacultyBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/digital-initiatives' | '/faculty-blog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/digital-initiatives' | '/faculty-blog'
  id: '__root__' | '/' | '/digital-initiatives' | '/faculty-blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalInitiativesRoute: typeof DigitalInitiativesRoute
  FacultyBlogRoute: typeof FacultyBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faculty-blog': {
      id: '/faculty-blog'
      path: '/faculty-blog'
      fullPath: '/faculty-blog'
      preLoaderRoute: typeof FacultyBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-initiatives': {
      id: '/digital-initiatives'
      path: '/digital-initiatives'
      fullPath: '/digital-initiatives'
      preLoaderRoute: typeof DigitalInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalInitiativesRoute: DigitalInitiativesRoute,
  FacultyBlogRoute: FacultyBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
